

export const rows: any[] = [
    {
        id: 1,
        nome: 'João Silva',
        email: 'joao.silva@empresa.com',
        tipo_usuario: 'Admin',
        cargo: 'Analista de Sistemas',
        encarregado: 'Maria Souza',
        gestor: 'Carlos Mendes',
        status: 'ativo',
        localizacao: "Alto Forno 3",
        data_criacao: '2023-01-15',
        data_inicio: '2023-01-15',
        data_fim: "2023-12-31",
        epi_responsabilidade: ["Capacete", "Óculos", "Luvas", "Botas", "Protetor Auricular"],
        equipamento: ["Furadeira", "Serra", "Martelo", "Chave de Fenda"],
        maquina: ["Escavadeira", "Betoneira", "Guindaste", "Compactadora"],
        produtos: ["Cimento", "Tijolos", "Areia", "Argamassa"],
        ultimo_acesso: '2023-06-28T14:30:00',
        foto: 'https://media.istockphoto.com/id/1494257384/pt/foto/construction-worker-in-portrait-man-with-crossed-arms-and-smile-architect-or-engineer-in.jpg?b=1&s=612x612&w=0&k=20&c=G_A5bA1quQGwqQ6iK52HWqw-x5JmPYfYWHXJE8q0zgc='
    },
    {
        id: 2,
        nome: 'Maria Souza',
        email: 'maria.souza@empresa.com',
        tipo_usuario: 'Gestão',
        cargo: 'Gerente de TI',
        encarregado: 'Carlos Mendes',
        gestor_responsavel: 'Carlos Mendes',
        status: 'ativo',
        localizacao: "Alto Forno 3",
        data_criacao: '2022-11-10',
        data_inicio: '2023-01-15',
        data_fim: "2023-12-31",
        epi_responsabilidade: ["Capacete", "Óculos", "Luvas", "Botas", "Protetor Auricular"],
        equipamento: ["Furadeira", "Serra", "Martelo", "Chave de Fenda"],
        maquina: ["Escavadeira", "Betoneira", "Guindaste", "Compactadora"],
        produtos: ["Cimento", "Tijolos", "Areia", "Argamassa"],
        ultimo_acesso: '2023-06-28T09:15:00',
        foto: 'https://media.istockphoto.com/id/2187765095/pt/foto/engineer-in-hard-hat-on-grey-background.jpg?s=612x612&w=0&k=20&c=RIrvozIJjzV32iChh7aYWxFObXs_4MllAIGCBtTjmEI='
    },
    {
        id: 3,
        nome: 'Pedro Oliveira',
        email: 'pedro.oliveira@empresa.com',
        tipo_usuario: 'Gestão',
        cargo: 'Desenvolvedor Front-end',
        encarregado: 'Maria Souza',
        gestor_responsavel: 'Carlos Mendes',
        status: 'ativo',
        localizacao: "Alto Forno 3",
        data_criacao: '2023-03-22',
        data_inicio: '2023-01-15',
        data_fim: "2023-12-31",
        epi_responsabilidade: ["Capacete", "Óculos", "Luvas", "Botas", "Protetor Auricular"],
        equipamento: ["Furadeira", "Serra", "Martelo", "Chave de Fenda"],
        maquina: ["Escavadeira", "Betoneira", "Guindaste", "Compactadora"],
        produtos: ["Cimento", "Tijolos", "Areia", "Argamassa"],
        ultimo_acesso: '2023-06-27T16:45:00',
        foto: 'https://media.istockphoto.com/id/2187765094/pt/foto/engineer-in-hard-hat-on-white-background.jpg?s=612x612&w=0&k=20&c=Qg9cqSDnPdcDPDm-d6QlwQly5TTYOegTzRBkhxijmdk='
    },
    {
        id: 4,
        nome: 'Ana Costa',
        email: 'ana.costa@empresa.com',
        tipo_usuario: 'Gestão',
        cargo: 'Designer UX/UI',
        encarregado: 'Carlos Mendes',
        gestor_responsavel: 'Carlos Mendes',
        status: 'inativo',
        localizacao: "Alto Forno 3",
        data_criacao: '2023-02-18',
        data_inicio: '2023-01-15',
        data_fim: "2023-12-31",
        epi_responsabilidade: ["Capacete", "Óculos", "Luvas", "Botas", "Protetor Auricular"],
        equipamento: ["Furadeira", "Serra", "Martelo", "Chave de Fenda"],
        maquina: ["Escavadeira", "Betoneira", "Guindaste", "Compactadora"],
        produtos: ["Cimento", "Tijolos", "Areia", "Argamassa"],
        ultimo_acesso: '2023-05-10T11:20:00',
        foto: 'https://media.istockphoto.com/id/670472538/pt/foto/studio-shot-of-young-happy-persian-man-construction-worker-smiling-while-wearing-eyeglasses.jpg?s=612x612&w=0&k=20&c=e-Et7jqzV4iP1AiIr3WuKgGkLyhpYSAhvI-xlAxhPew='
    },
    {
        id: 5,
        nome: 'Carlos Mendes',
        email: 'carlos.mendes@empresa.com',
        tipo_usuario: 'Admin',
        cargo: 'Diretor de Tecnologia',
        encarregado: 'CEO',
        gestor_responsavel: 'Carlos Mendes',
        status: 'ativo',
        localizacao: "Alto Forno 3",
        data_criacao: '2021-08-05',
        data_inicio: '2023-01-15',
        data_fim: "2023-12-31",
        epi_responsabilidade: ["Capacete", "Óculos", "Luvas", "Botas", "Protetor Auricular"],
        equipamento: ["Furadeira", "Serra", "Martelo", "Chave de Fenda"],
        maquina: ["Escavadeira", "Betoneira", "Guindaste", "Compactadora"],
        produtos: ["Cimento", "Tijolos", "Areia", "Argamassa"],
        ultimo_acesso: '2023-06-28T10:00:00',
        foto: 'https://media.istockphoto.com/id/1494257384/pt/foto/construction-worker-in-portrait-man-with-crossed-arms-and-smile-architect-or-engineer-in.jpg?b=1&s=612x612&w=0&k=20&c=G_A5bA1quQGwqQ6iK52HWqw-x5JmPYfYWHXJE8q0zgc='
    },
    {
        id: 6,
        nome: 'Fernanda Lima',
        email: 'fernanda.lima@empresa.com',
        tipo_usuario: 'Gestão',
        cargo: 'Analista de Dados',
        encarregado: 'Maria Souza',
        gestor_responsavel: 'Carlos Mendes',
        status: 'ativo',
        localizacao: "Alto Forno 3",
        data_criacao: '2023-04-30',
        data_inicio: '2023-01-15',
        data_fim: "2023-12-31",
        epi_responsabilidade: ["Capacete", "Óculos", "Luvas", "Botas", "Protetor Auricular"],
        equipamento: ["Furadeira", "Serra", "Martelo", "Chave de Fenda"],
        maquina: ["Escavadeira", "Betoneira", "Guindaste", "Compactadora"],
        produtos: ["Cimento", "Tijolos", "Areia", "Argamassa"],
        ultimo_acesso: '2023-06-28T13:45:00',
        foto: 'https://media.istockphoto.com/id/1494257384/pt/foto/construction-worker-in-portrait-man-with-crossed-arms-and-smile-architect-or-engineer-in.jpg?b=1&s=612x612&w=0&k=20&c=G_A5bA1quQGwqQ6iK52HWqw-x5JmPYfYWHXJE8q0zgc='
    },
    {
        id: 7,
        nome: 'Ricardo Alves',
        email: 'ricardo.alves@empresa.com',
        tipo_usuario: 'Admin',
        cargo: 'Desenvolvedor Back-end',
        encarregado: 'Maria Souza',
        gestor_responsavel: 'Carlos Mendes',
        status: 'inativo',
        localizacao: "Alto Forno 3",
        data_criacao: '2023-01-10',
        data_inicio: '2023-01-15',
        data_fim: "2023-12-31",
        epi_responsabilidade: ["Capacete", "Óculos", "Luvas", "Botas", "Protetor Auricular"],
        equipamento: ["Furadeira", "Serra", "Martelo", "Chave de Fenda"],
        maquina: ["Escavadeira", "Betoneira", "Guindaste", "Compactadora"],
        produtos: ["Cimento", "Tijolos", "Areia", "Argamassa"],
        ultimo_acesso: '2023-04-15T14:30:00',
        foto: 'https://media.istockphoto.com/id/1494257384/pt/foto/construction-worker-in-portrait-man-with-crossed-arms-and-smile-architect-or-engineer-in.jpg?b=1&s=612x612&w=0&k=20&c=G_A5bA1quQGwqQ6iK52HWqw-x5JmPYfYWHXJE8q0zgc='
    },
    {
        id: 8,
        nome: 'Juliana Santos',
        email: 'juliana.santos@empresa.com',
        tipo_usuario: 'Admin',
        cargo: 'Product Owner',
        encarregado: 'Carlos Mendes',
        gestor_responsavel: 'Carlos Mendes',
        status: 'ativo',
        localizacao: "Alto Forno 3",
        data_criacao: '2022-09-12',
        data_inicio: '2023-01-15',
        data_fim: "2023-12-31",
        epi_responsabilidade: ["Capacete", "Óculos", "Luvas", "Botas", "Protetor Auricular"],
        equipamento: ["Furadeira", "Serra", "Martelo", "Chave de Fenda"],
        maquina: ["Escavadeira", "Betoneira", "Guindaste", "Compactadora"],
        produtos: ["Cimento", "Tijolos", "Areia", "Argamassa"],
        ultimo_acesso: '2023-06-28T08:30:00',
        foto: 'https://media.istockphoto.com/id/1494257384/pt/foto/construction-worker-in-portrait-man-with-crossed-arms-and-smile-architect-or-engineer-in.jpg?b=1&s=612x612&w=0&k=20&c=G_A5bA1quQGwqQ6iK52HWqw-x5JmPYfYWHXJE8q0zgc='
    },
    {
        id: 9,
        nome: 'Marcos Pereira',
        email: 'marcos.pereira@empresa.com',
        tipo_usuario: 'Gestão',
        cargo: 'QA Engineer',
        encarregado: 'Maria Souza',
        gestor_responsavel: 'Carlos Mendes',
        status: 'ativo',
        localizacao: "Alto Forno 3",
        data_criacao: '2023-05-15',
        data_inicio: '2023-01-15',
        data_fim: "2023-12-31",
        epi_responsabilidade: ["Capacete", "Óculos", "Luvas", "Botas", "Protetor Auricular"],
        equipamento: ["Furadeira", "Serra", "Martelo", "Chave de Fenda"],
        maquina: ["Escavadeira", "Betoneira", "Guindaste", "Compactadora"],
        produtos: ["Cimento", "Tijolos", "Areia", "Argamassa"],
        ultimo_acesso: '2023-06-27T17:20:00',
        foto: 'https://media.istockphoto.com/id/1494257384/pt/foto/construction-worker-in-portrait-man-with-crossed-arms-and-smile-architect-or-engineer-in.jpg?b=1&s=612x612&w=0&k=20&c=G_A5bA1quQGwqQ6iK52HWqw-x5JmPYfYWHXJE8q0zgc='
    },
    {
        id: 10,
        nome: 'Patricia Nunes',
        email: 'patricia.nunes@empresa.com',
        tipo_usuario: 'Admin',
        cargo: 'Analista de Negócios',
        encarregado: 'Carlos Mendes',
        gestor_responsavel: 'Carlos Mendes',
        status: 'inativo',
        localizacao: "Alto Forno 3",
        data_criacao: '2022-12-01',
        data_inicio: '2023-01-15',
        data_fim: "2023-12-31",
        epi_responsabilidade: ["Capacete", "Óculos", "Luvas", "Botas", "Protetor Auricular"],
        equipamento: ["Furadeira", "Serra", "Martelo", "Chave de Fenda"],
        maquina: ["Escavadeira", "Betoneira", "Guindaste", "Compactadora"],
        produtos: ["Cimento", "Tijolos", "Areia", "Argamassa"],
        ultimo_acesso: '2023-03-20T10:15:00',
        foto: 'https://media.istockphoto.com/id/1494257384/pt/foto/construction-worker-in-portrait-man-with-crossed-arms-and-smile-architect-or-engineer-in.jpg?b=1&s=612x612&w=0&k=20&c=G_A5bA1quQGwqQ6iK52HWqw-x5JmPYfYWHXJE8q0zgc='
    },
    {
        id: 11,
        nome: 'João Silva',
        email: 'joao.silva@empresa.com',
        tipo_usuario: 'Gestão',
        cargo: 'Analista de Sistemas',
        encarregado: 'Maria Souza',
        gestor_responsavel: 'Carlos Mendes',
        status: 'ativo',
        localizacao: "Alto Forno 3",
        data_criacao: '2023-01-15',
        data_inicio: '2023-01-15',
        data_fim: "2023-12-31",
        epi_responsabilidade: ["Capacete", "Óculos", "Luvas", "Botas", "Protetor Auricular"],
        equipamento: ["Furadeira", "Serra", "Martelo", "Chave de Fenda"],
        maquina: ["Escavadeira", "Betoneira", "Guindaste", "Compactadora"],
        produtos: ["Cimento", "Tijolos", "Areia", "Argamassa"],
        ultimo_acesso: '2023-06-28T14:30:00',
        foto: 'https://media.istockphoto.com/id/1494257384/pt/foto/construction-worker-in-portrait-man-with-crossed-arms-and-smile-architect-or-engineer-in.jpg?b=1&s=612x612&w=0&k=20&c=G_A5bA1quQGwqQ6iK52HWqw-x5JmPYfYWHXJE8q0zgc='
    },
    {
        id: 12,
        nome: 'Maria Souza',
        email: 'maria.souza@empresa.com',
        tipo_usuario: 'Gestão',
        cargo: 'Gerente de TI',
        encarregado: 'Carlos Mendes',
        gestor_responsavel: 'Carlos Mendes',
        status: 'ativo',
        localizacao: "Alto Forno 3",
        data_criacao: '2022-11-10',
        data_inicio: '2023-01-15',
        data_fim: "2023-12-31",
        epi_responsabilidade: ["Capacete", "Óculos", "Luvas", "Botas", "Protetor Auricular"],
        equipamento: ["Furadeira", "Serra", "Martelo", "Chave de Fenda"],
        maquina: ["Escavadeira", "Betoneira", "Guindaste", "Compactadora"],
        produtos: ["Cimento", "Tijolos", "Areia", "Argamassa"],
        ultimo_acesso: '2023-06-28T09:15:00',
        foto: 'https://media.istockphoto.com/id/1494257384/pt/foto/construction-worker-in-portrait-man-with-crossed-arms-and-smile-architect-or-engineer-in.jpg?b=1&s=612x612&w=0&k=20&c=G_A5bA1quQGwqQ6iK52HWqw-x5JmPYfYWHXJE8q0zgc='
    },
    {
        id: 13,
        nome: 'Pedro Oliveira',
        email: 'pedro.oliveira@empresa.com',
        tipo_usuario: 'Gestão',
        cargo: 'Desenvolvedor Front-end',
        encarregado: 'Maria Souza',
        gestor_responsavel: 'Carlos Mendes',
        status: 'ativo',
        localizacao: "Alto Forno 3",
        data_criacao: '2023-03-22',
        data_inicio: '2023-01-15',
        data_fim: "2023-12-31",
        epi_responsabilidade: ["Capacete", "Óculos", "Luvas", "Botas", "Protetor Auricular"],
        equipamento: ["Furadeira", "Serra", "Martelo", "Chave de Fenda"],
        maquina: ["Escavadeira", "Betoneira", "Guindaste", "Compactadora"],
        produtos: ["Cimento", "Tijolos", "Areia", "Argamassa"],
        ultimo_acesso: '2023-06-27T16:45:00',
        foto: 'https://media.istockphoto.com/id/1494257384/pt/foto/construction-worker-in-portrait-man-with-crossed-arms-and-smile-architect-or-engineer-in.jpg?b=1&s=612x612&w=0&k=20&c=G_A5bA1quQGwqQ6iK52HWqw-x5JmPYfYWHXJE8q0zgc='
    },
    {
        id: 14,
        nome: 'Ana Costa',
        email: 'ana.costa@empresa.com',
        tipo_usuario: 'Gestão',
        cargo: 'Designer UX/UI',
        encarregado: 'Carlos Mendes',
        gestor_responsavel: 'Carlos Mendes',
        status: 'inativo',
        localizacao: "Alto Forno 3",
        data_criacao: '2023-02-18',
        data_inicio: '2023-01-15',
        data_fim: "2023-12-31",
        epi_responsabilidade: ["Capacete", "Óculos", "Luvas", "Botas", "Protetor Auricular"],
        equipamento: ["Furadeira", "Serra", "Martelo", "Chave de Fenda"],
        maquina: ["Escavadeira", "Betoneira", "Guindaste", "Compactadora"],
        produtos: ["Cimento", "Tijolos", "Areia", "Argamassa"],
        ultimo_acesso: '2023-05-10T11:20:00',
        foto: 'https://media.istockphoto.com/id/1494257384/pt/foto/construction-worker-in-portrait-man-with-crossed-arms-and-smile-architect-or-engineer-in.jpg?b=1&s=612x612&w=0&k=20&c=G_A5bA1quQGwqQ6iK52HWqw-x5JmPYfYWHXJE8q0zgc='
    },
    {
        id: 15,
        nome: 'Carlos Mendes',
        email: 'carlos.mendes@empresa.com',
        tipo_usuario: 'Admin',
        cargo: 'Diretor de Tecnologia',
        encarregado: 'CEO',
        gestor_responsavel: 'Carlos Mendes',
        status: 'ativo',
        localizacao: "Alto Forno 3",
        data_criacao: '2021-08-05',
        data_inicio: '2023-01-15',
        data_fim: "2023-12-31",
        epi_responsabilidade: ["Capacete", "Óculos", "Luvas", "Botas", "Protetor Auricular"],
        equipamento: ["Furadeira", "Serra", "Martelo", "Chave de Fenda"],
        maquina: ["Escavadeira", "Betoneira", "Guindaste", "Compactadora"],
        produtos: ["Cimento", "Tijolos", "Areia", "Argamassa"],
        ultimo_acesso: '2023-06-28T10:00:00',
        foto: 'https://media.istockphoto.com/id/1494257384/pt/foto/construction-worker-in-portrait-man-with-crossed-arms-and-smile-architect-or-engineer-in.jpg?b=1&s=612x612&w=0&k=20&c=G_A5bA1quQGwqQ6iK52HWqw-x5JmPYfYWHXJE8q0zgc='
    },
    {
        id: 16,
        nome: 'Fernanda Lima',
        email: 'fernanda.lima@empresa.com',
        tipo_usuario: 'Admin',
        cargo: 'Analista de Dados',
        encarregado: 'Maria Souza',
        gestor_responsavel: 'Carlos Mendes',
        status: 'ativo',
        localizacao: "Alto Forno 3",
        data_criacao: '2023-04-30',
        data_inicio: '2023-01-15',
        data_fim: "2023-12-31",
        epi_responsabilidade: ["Capacete", "Óculos", "Luvas", "Botas", "Protetor Auricular"],
        equipamento: ["Furadeira", "Serra", "Martelo", "Chave de Fenda"],
        maquina: ["Escavadeira", "Betoneira", "Guindaste", "Compactadora"],
        produtos: ["Cimento", "Tijolos", "Areia", "Argamassa"],
        ultimo_acesso: '2023-06-28T13:45:00',
        foto: 'https://media.istockphoto.com/id/1494257384/pt/foto/construction-worker-in-portrait-man-with-crossed-arms-and-smile-architect-or-engineer-in.jpg?b=1&s=612x612&w=0&k=20&c=G_A5bA1quQGwqQ6iK52HWqw-x5JmPYfYWHXJE8q0zgc='
    },
    {
        id: 17,
        nome: 'Ricardo Alves',
        email: 'ricardo.alves@empresa.com',
        tipo_usuario: 'Gestão',
        cargo: 'Desenvolvedor Back-end',
        encarregado: 'Maria Souza',
        gestor_responsavel: 'Carlos Mendes',
        status: 'inativo',
        localizacao: "Alto Forno 3",
        data_criacao: '2023-01-10',
        data_inicio: '2023-01-15',
        data_fim: "2023-12-31",
        epi_responsabilidade: ["Capacete", "Óculos", "Luvas", "Botas", "Protetor Auricular"],
        equipamento: ["Furadeira", "Serra", "Martelo", "Chave de Fenda"],
        maquina: ["Escavadeira", "Betoneira", "Guindaste", "Compactadora"],
        produtos: ["Cimento", "Tijolos", "Areia", "Argamassa"],
        ultimo_acesso: '2023-04-15T14:30:00',
        foto: 'https://media.istockphoto.com/id/1494257384/pt/foto/construction-worker-in-portrait-man-with-crossed-arms-and-smile-architect-or-engineer-in.jpg?b=1&s=612x612&w=0&k=20&c=G_A5bA1quQGwqQ6iK52HWqw-x5JmPYfYWHXJE8q0zgc='
    },
    {
        id: 18,
        nome: 'Juliana Santos',
        email: 'juliana.santos@empresa.com',
        tipo_usuario: 'Geestão',
        cargo: 'Product Owner',
        encarregado: 'Carlos Mendes',
        gestor_responsavel: 'Carlos Mendes',
        status: 'ativo',
        localizacao: "Alto Forno 3",
        data_criacao: '2022-09-12',
        data_inicio: '2023-01-15',
        data_fim: "2023-12-31",
        epi_responsabilidade: ["Capacete", "Óculos", "Luvas", "Botas", "Protetor Auricular"],
        equipamento: ["Furadeira", "Serra", "Martelo", "Chave de Fenda"],
        maquina: ["Escavadeira", "Betoneira", "Guindaste", "Compactadora"],
        produtos: ["Cimento", "Tijolos", "Areia", "Argamassa"],
        ultimo_acesso: '2023-06-28T08:30:00',
        foto: 'https://media.istockphoto.com/id/1494257384/pt/foto/construction-worker-in-portrait-man-with-crossed-arms-and-smile-architect-or-engineer-in.jpg?b=1&s=612x612&w=0&k=20&c=G_A5bA1quQGwqQ6iK52HWqw-x5JmPYfYWHXJE8q0zgc='
    },
    {
        id: 19,
        nome: 'Marcos Pereira',
        email: 'marcos.pereira@empresa.com',
        tipo_usuario: 'Admin',
        cargo: 'QA Engineer',
        encarregado: 'Maria Souza',
        gestor_responsavel: 'Carlos Mendes',
        status: 'ativo',
        localizacao: "Alto Forno 3",
        data_criacao: '2023-05-15',
        data_inicio: '2023-01-15',
        data_fim: "2023-12-31",
        epi_responsabilidade: ["Capacete", "Óculos", "Luvas", "Botas", "Protetor Auricular"],
        equipamento: ["Furadeira", "Serra", "Martelo", "Chave de Fenda"],
        maquina: ["Escavadeira", "Betoneira", "Guindaste", "Compactadora"],
        produtos: ["Cimento", "Tijolos", "Areia", "Argamassa"],
        ultimo_acesso: '2023-06-27T17:20:00',
        foto: 'https://media.istockphoto.com/id/1494257384/pt/foto/construction-worker-in-portrait-man-with-crossed-arms-and-smile-architect-or-engineer-in.jpg?b=1&s=612x612&w=0&k=20&c=G_A5bA1quQGwqQ6iK52HWqw-x5JmPYfYWHXJE8q0zgc='
    },
    {
        id: 20,
        nome: 'Patricia Nunes',
        email: 'patricia.nunes@empresa.com',
        tipo_usuario: 'Admin',
        cargo: 'Analista de Negócios',
        encarregado: 'Carlos Mendes',
        gestor_responsavel: 'Carlos Mendes',
        status: 'inativo',
        localizacao: "Alto Forno 3",
        data_criacao: '2022-12-01',
        data_inicio: '2023-01-15',
        data_fim: "2023-12-31",
        epi_responsabilidade: ["Capacete", "Óculos", "Luvas", "Botas", "Protetor Auricular"],
        equipamento: ["Furadeira", "Serra", "Martelo", "Chave de Fenda"],
        maquina: ["Escavadeira", "Betoneira", "Guindaste", "Compactadora"],
        produtos: ["Cimento", "Tijolos", "Areia", "Argamassa"],
        ultimo_acesso: '2023-03-20T10:15:00,',
        foto: 'https://media.istockphoto.com/id/1494257384/pt/foto/construction-worker-in-portrait-man-with-crossed-arms-and-smile-architect-or-engineer-in.jpg?b=1&s=612x612&w=0&k=20&c=G_A5bA1quQGwqQ6iK52HWqw-x5JmPYfYWHXJE8q0zgc='
    }
];

