name: Deploy Front-End Docker

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      # Copiar arquivos main para a máquina 1
      - name: Copiar arquivos main para o servidor
        if: github.ref == 'refs/heads/main'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22206
          source: "."
          target: "/var/www/nowaste-front-end"
          exclude: |
            .git*
            node_modules
            *.log
          strip_components: 1
          overwrite: true

      # Copiar arquivos dev para a máquina 2 (DEV)
      - name: Copiar arquivos dev para o servidor
        if: github.ref == 'refs/heads/dev'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY_DEV }}
          port: 22207
          source: "."
          target: "/var/www/nowastev2-homologa"
          debug: true
          exclude: |
            .git*
            node_modules
            *.log
          strip_components: 1
          overwrite: true

      # SSH e rodar Docker na máquina 1 (main)
      - name: SSH e rodar Docker main
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 22206
          script: |
            cd /var/www/nowaste-front-end
            docker stop nowaste-front-end || true
            docker rm nowaste-front-end || true
            docker build -t nowaste-front-end .
            docker run -d -p 9003:18649 --name nowaste-front-end nowaste-front-end

      # SSH e rodar Docker na máquina 2 (dev)
      - name: SSH e rodar Docker dev
        if: github.ref == 'refs/heads/dev'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY_DEV }}
          port: 22207
          script: |
            cd /var/www/nowastev2-homologa
            docker stop nowastev2-homologa || true
            docker rm nowastev2-homologa || true
            docker build -t nowastev2-homologa .
            docker run -d -p 9003:18649 --name nowastev2-homologa nowastev2-homologa
